
***********************************************************************
 Starting job:

    Name:              method_compare
    ID:                931330
    Hostname:          n085
    Working directory: /home/vulcan/cgb31826/git/Dimagnesocene

    Submitted using:   submit --array 1-64 -N method_compare -i in/be_bond_compare.in -o in/be_bond_compare.out gen4.q psi4@master
***********************************************************************
module load  psi4-master-intel-16.0.1-avducsgnonqrcpftiesq432gagal6y7r
Traceback (most recent call last):
  File "/opt/psi/4/1.9a/bin/psi4", line 372, in <module>
    exec(content)
  File "<string>", line 61, in <module>
  File "/opt/psi/4/1.9a/lib/psi4/driver/driver.py", line 526, in energy
    wfn = procedures['energy'][lowername](lowername, molecule=molecule, **kwargs)
  File "/opt/psi/4/1.9a/lib/psi4/driver/procrouting/proc.py", line 1105, in select_cisd
    return func(name, **kwargs)
  File "/opt/psi/4/1.9a/lib/psi4/driver/procrouting/proc.py", line 5357, in run_cepa
    fnocc_wfn = core.fnocc(ref_wfn)

RuntimeError: 
Fatal Error: PSIO_ERROR: 6 (file is already open)

Error occurred in file: /tmp/psi4/psi4/src/psi4/libpsio/error.cc on line: 134
The most recent 5 function calls were:

psi::PsiException::PsiException(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, char const*, int)
psi::PSIO::open(unsigned long, int)


Printing out the relevant lines from the Psithon --> Python processed input file:
    methods = ["hf", "mp2", "b3lyp", "b97-1", "pw6b95", "cisd", "ccsd", "dsd-b3lyp-d3bj"]
    basis_sets = ["cc-pVDZ", "aug-cc-pVDZ", "pcsseg-3", "aug-pcsseg-3", "aug-pcsseg-4", "cc-pVTZ", "def2-tzvp", "sad-fit"]
    basis = basis_sets[(int(os.environ["SGE_TASK_ID"]) - 1) % len(basis_sets)]
    method = methods[(int(os.environ["SGE_TASK_ID"]) - 1) // len(basis_sets)]
    start_time = time.time()
--> en = energy(method + "/" + basis)
    ideal_en = -416.31749560
    try :
        optimize(method + "/" + basis)
    except psi4.driver.p4util.OptimizationConvergenceError as e :
        task_id = os.environ["SGE_TASK_ID"]


!----------------------------------------------------------------------------------!
!                                                                                  !
! Fatal Error: PSIO_ERROR: 6 (file is already open)                                !
! Error occurred in file: /tmp/psi4/psi4/src/psi4/libpsio/error.cc on line: 134    !
! The most recent 5 function calls were:                                           !
! psi::PsiException::PsiException(std::__cxx11::basic_string<char,                 !
!     std::char_traits<char>, std::allocator<char> >, char const*, int)            !
! psi::PSIO::open(unsigned long, int)                                              !
!                                                                                  !
!----------------------------------------------------------------------------------!

